apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hands-on
    environment: prod
    version: "1.0.0"
  name: hands-on
  namespace: Bteam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hands-on
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hands-on
    spec:
      containers:
      - name: foobar
        image: nginx:latest
        env:
        - name: DB_HOST
          value: "192.168.0.1"
        - name: DB_NAME
          value: "foobar"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources: 
          requests:
            cpu: "10m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          tcpSocket:
            port: 80
            host: <default-to-pod-ip>
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
            httpHeaders:
            - name: kubelet-probe
              value: "true"